services:
    server:
        build: ./backend
        expose:
            - 8000
        ports:
            - 8000:8000
        volumes:
            - ./backend/src:/app/server/src  
        command: npm run dev

    client:
        build: ./frontend
        expose:
            - 3000   
        ports:
            - 4200:3000
        volumes:
            - ./frontend/src:/app/client/src
            - ./frontend/public:/app/client/public
        depends_on:
            - server  
        stdin_open: true
        command: npm run start